version: "3.8"

services:
  web:
    container_name: api
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "4000:5000"
    environment:
      - PORT=5000
    depends_on:
      - postgesql
    restart: always
    volumes:
      - ./:/app
    networks:
      - web_api

  postgesql:
    image: postgis/postgis:14-3.3-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spots_db
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - web_api

volumes:
  db:
    driver: local

networks:
  web_api:
    driver: bridge